const express = require('express');
const authMiddleware = require('../middleware/authMiddleware');
const { isCustomer } = require('../middleware/roleMiddleware');
const { getCart, addItem, updateItem, removeItem, clearCart } = require('../controllers/cartController');
const router = express.Router();
router.use(authMiddleware, isCustomer);
router.get('/', getCart);
router.post('/items', addItem);
router.put('/items/:itemId', updateItem);
router.delete('/items/:itemId', removeItem);
router.delete('/', clearCart);
module.exports = router;
